# This is the configuration used to check the rubocop source code.
inherit_from: #{RUBOCOP_HOME}/config/default.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/**/*'
    - 'Guardfile'
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 20

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashConversion:
  Enabled: true

Style/Next:
  Enabled: false

Style/OptionalArguments:
  Enabled: false

Style/RedundantStringEscape:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  AllowPredicates: true

Style/WordArray:
  Enabled: false