# This is the configuration used to check the rubocop source code.
inherit_from: #{RUBOCOP_HOME}/config/default.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*'
    - 'Guardfile'

CyclomaticComplexity: 
  Max: 15

PerceivedComplexity:
  Max: 20

MethodLength:
  Max: 30

ClassLength:
  Enabled: false

LineLength:
  Max: 150

WordArray:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

CommentAnnotation:
  Enabled: false

Documentation:
  Enabled: false

Next:
  Enabled: false

OptionalArguments:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

SignalException:
  EnforcedStyle: only_raise

TrivialAccessors:
  AllowPredicates: true

BlockNesting:
  Max: 4

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
