language: ruby
cache: bundler
rvm: 2.4
before_install:
  - gem update --system
  - gem install bundler
script:
- bundle exec bundle-audit update && bundle exec bundle-audit check
- bundle exec rspec
- bundle exec rubocop lib spec
deploy:
  - provider: releases
    api_key:
      secure: z/GBmPIgX/UQLixhUnN6fouJbC0PghjW8MeAJJoeIPNqKuv2Kws1wgNOndgrSb+U/gfIZ8CAHTq/U6hlfpGHt7+IBAmO/YMCH/O0CV/MNCfVKwduFTZplcDSnXAiFy77yk+ute0It/L/HJO1LMSq3q1wU2jUWL4CZal/+GY7yVFo8EZQJBeTmvatPd0uD+/+bFwEsYEGKt2/JF42GW6Xtbt9DHXwL1olYmReuPjXavdomZof0KKboM+cI42gzJ5AYVl4ouELGiGQgh5dgK1HkvpBGYqg16YgT0LK5HnQ24slwJk2+yM6x9bXZqQu8IEhPafxR77wJ6T0388iM5vCXtzzJidsOL6mANqpKZ8z1YsAi0w4QNAPvf2AFw40fIfu2W/J4z2UYQUKD/3Em1IY0/fPr+FdMBMWQNevjjns89943GWhFoDUJj4EMt46rEpMHPVTA9DfUA7be4IRo9YrUx7u8MaVotpzSYCxepAmC9tB7KQAjygxI7z/orihZj7lHadUI8rPKfKUkrDDwSyB8xyV5BjpcorSshoqnFLaGrxHfbos/ww5i2xxQEF77RK9rkaICyE7q6oOghCq7BSKsYVzNkBCtRftVy5zYCEPd8MCXxF40S3uv4ta30wQKhdZPWELf4GkzKxCpdbbryWQKoF6ZKceD+LIG18qVlO5AqU=
    file_glob: true
    file: hedgelog-*.gem
    on:
      tags: true
      repo: firespring/hedgelog
  - provider: rubygems
    api_key:
      secure: anM34Z3fd3H5xt46pVbOmC0FnPsD0Pro9+Vmdv4fq22GvjFolexCtNFt8fb8V+M9THvw1qZDvSyHTZ0NKUDMqaVLX+VhDvquhuM0vviAECBu7kqqZ/pBjBJduYrtcFrCpoL3vs3AhXM882XKIhw4YMtOgoh00DpLZYQbtdEVvCZhbIe80N2eRSM1taVNQQwkI7pREBBFliBrjpP82Vfacue7m/iDKg/k1SRv1jXafQLDM0k8UAdYntc/popqTpXCbmxOcPVv6yVghijld6rTirLeRSrbwq1m0Djg24r/BGd8NsFn9Xtvtm8oZN3Xv2Q8AoJFeDCymTndUtJYrFaS8IQe5TLzXLYW+/BjedCuA09bfcRjW7vjuO73yYqf/K+dTbwbuJMpUJt6Mymu66MuPi6ntj00hvDBU9ekHFkZlemUixq3LxvmEPyxK8PKTLVH9UipkTBG0cXWct5fCXhv0KvrxFLeZM2XXqvknnuYGSIE5fvGLHvn2OuX5JESJzwDt8xBNXrPmCIcDX/DOONR+AuPYQkDLybM75/P+vnxSfT6ZMFj7AxZAr23mWOQ1dK+dgvJb+nbBa+5KRCPs9n9M4aW5ybNKgy8v8Mgp6ebTuRLYDUdOB2aMXRy6/0dqSMR+fe0B7HtHXNtp73Nidox6QBFQzmtXg8fzsXA9yFKFZI=
    gem: hedgelog
    on:
      tags: true
      repo: firespring/hedgelog
